<?php
//
// File generated by Dolibarr installer 11.0.0-alpha on 14 nov. 2019
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
/*$dolibarr_main_url_root='http://dolibarr.local';
$dolibarr_main_document_root='C:/xampp/htdocs/dolibarr';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='C:/xampp/htdocs/dolibarr/custom';
$dolibarr_main_data_root='C:/xampp/htdocs/dolibarr/documents';
$dolibarr_main_db_host='mysql521int.srv-hostalia.com';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='db5210912_doli';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='u5210912_doli';
$dolibarr_main_db_pass='BdI9wgYFV9';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_bin';
// Authentication settings
$dolibarr_main_authentication='dolibarr';*/
$dolibarr_main_url_root='http://dolibarr.local';
$dolibarr_main_document_root='C:/xampp/htdocs/dolibarr_defi';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='C:/xampp/htdocs/dolibarr_defi/custom';
$dolibarr_main_data_root='C:/xampp/htdocs/dolibarr_defi/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='dolibarrrpm';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_bin';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='0b9d77c9d2e9f4e2fd4f7b7d0463b3d1';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
//VASA configuracions
$rutaIcones='/responsiveModule/img/menuicon/';